allow:
    teleport: true
    messaging: true
    lifesigns: true
    beacon: true
worlds:
    world: true
recipe:
    shape: BBG,WOC,III
    ingredients:
        B: STONE_BUTTON
        G: GLASS
        W: WATCH
        O: GOLD_INGOT
        C: COMPASS
        I: IRON_INGOT
    result: WATCH
    amount: 1
    lore: "Cheap and nasty time travel"
tachyon_use:
    max: 1000
    recharge: 25
    recharge_interval: 600
    travel:
        random: 100
        world: 150
        coords: 200
        saved: 50
    lifesigns: 15
    beacon: 1000
storage:
  database: sqlite
  mysql:
    url: mysql://localhost:3306/TARDIS
    user: bukkit
    password: mysecurepassword
date_format: dd/mn/YY HH:mm
respect:
    worldborder: true
    worldguard: true
    griefprevention: true
    factions: true
    towny: true
debug: false