authors: [ eccentric_nz ]
main: me.eccentric_nz.tardisvortexmanipulator.TardisVortexManipulatorPlugin
name: TARDISVortexManipulator
description: Vortex manipulator. Cheap and nasty time travel. Very bad for you. I'm trying to give it up.
version: ${project.version}
api-version: 1.17
load: POSTWORLD
depend: [ TARDIS ]
website: http://tardisjenkins.duckdns.org:8080/job/TARDISVortexManipulator/
dev-url: https://github.com/eccentricdevotion/TARDISVortexManipulator/
url: http://eccentricdevotion.github.io/TARDIS/
permissions:
  vm.teleport:
    description: Allow crafting and using of a Vortex Manipulator
    default: op
  vm.message:
    description: Allow Vortex Manipulator messaging
    default: op
  vm.lifesigns:
    description: Allow players to detect lifesigns and info on other players
  vm.beacon:
    description: Allow players to activate the Vortex Manipulator beacon
    default: op
  vm.lookatblock:
    description: Allow players to teleport to the block they are looking at
    default: op
commands:
  vortexmanipulator:
    aliases: [ vm,tvm ]
    description: Cheap and nasty time travel. Very bad for you.
    usage: /<command> [world] [x] [y] [z]
    permission: vm.teleport
    permission-message: You don't have the permission <permission> to use this command
  vmmessage:
    aliases: [ vmm,vmmsg ]
    description: Message other Vortex Manipulator users.
    usage: /<command> msg [player] [message], /<command> list [in|out] {page}, /<command> read [#], /<command> delete [#], /<command> clear [in|out]
    permission: vm.message
    permission-message: You don't have the permission <permission> to use this command
  vmsave:
    aliases: [ vms ]
    description: Save Vortex Manipulator location.
    usage: /<command> [save_name]
    permission: vm.teleport
    permission-message: You don't have the permission <permission> to use this command
  vmremove:
    aliases: [ vmr ]
    description: Remove Vortex Manipulator save.
    usage: /<command> [save_name]
    permission: vm.teleport
    permission-message: You don't have the permission <permission> to use this command
  vmhelp:
    aliases: [ vmh ]
    description: Vortex Manipulator help.
    usage: /<command> [topic]
  vmlifesigns:
    aliases: [ vml,vmlife ]
    description: Get Vortex Manipulator entity information.
    usage: /<command> [save_name]
    permission: vm.lifesigns
    permission-message: You don't have the permission <permission> to use this command
  vmbeacon:
    aliases: [ vmb ]
    description: Send out a Vortex Manipulator beacon signal.
    usage: /<command> [colour]
    permission: vm.beacon
    permission-message: You don't have the permission <permission> to use this command
  vmactivate:
    aliases: [ vma ]
    description: Activate a Vortex Manipulator that has been given with the /tardisgive command.
    usage: /<command> [player]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  vmgive:
    aliases: [ vmg ]
    description: Give Tachyon energy to a player's Vortex Manipulator.
    usage: /<command> [uuid] [amount]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  vmdatabase:
    aliases: [ vmd ]
    description: Transfer SQLite database records to MySQL.
    usage: /<command> convert_database
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
